apiVersion: v1
kind: Service
metadata:
  namespace: example
  labels:
    app: kubernetes-example
  name: kubernetes-example-svc
spec:
  ports:
    - name: hfp-svc-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kubernetes-example
  type: ClusterIP
