spring:
  datasource:
    url: jdbc:mysql://${SECRET_spring_datasource_url}:${SECRET_spring_datasource_port}/${SECRET_spring_datasource_schema}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&serverTimezone=UTC&rewriteBatchedStatements=true
    username: ${SECRET_spring_datasource_username}
    password: ${SECRET_spring_datasource_password}