apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: example
  name: kubernetes-example-mysql
spec:
  selector:
    matchLabels:
      app: kubernetes-example-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kubernetes-example-mysql
    spec:
      containers:
      - image: mysql:8.0
        name: kubernetes-example-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql