apiVersion: v1
kind: Secret
metadata:
  namespace: example
  name: mysql-secret                  # This name is how you will reference and access the Secret in other parts of your Kubernetes configuration.
type: Opaque
stringData:
  password: '123456'